--- Dependencies: ST_MainAxis, ST_Side

CREATE OR REPLACE FUNCTION rc.ApproxAuxLines (
		surface_id integer
	)
RETURNS VOID AS
$BODY$
	DECLARE 
		surface_centerline geometry;
	BEGIN
		SELECT ST_MainAxis(ST_Normalize(geom)) FROM rc.surface WHERE id = surface_id INTO surface_centerline;

		INSERT INTO rc.auxiliary_line (comment, autogenerated, geom) SELECT 'centerline of surface '|| surface_id, true, ST_Multi(ST_Force3D(surface_centerline));
		INSERT INTO rc.auxiliary_line (comment, autogenerated, geom) SELECT 'left side of surface '||  surface_id, true, ST_Multi(ST_Force3D(ST_Side(surface_centerline, geom, 'left'))) FROM rc.surface WHERE id = surface_id;
		INSERT INTO rc.auxiliary_line (comment, autogenerated, geom) SELECT 'right side of surface '|| surface_id, true, ST_Multi(ST_Force3D(ST_Side(surface_centerline, geom, 'right'))) FROM rc.surface WHERE id = surface_id;
		
		RETURN;
	END;
$BODY$ LANGUAGE plpgsql;